{{- if .Values.scanServer.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bjorn2scan.fullname" . }}-scan-server
  labels:
    {{- include "bjorn2scan.labels" . | nindent 4 }}
    app.kubernetes.io/component: scan-server
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]
{{- if .Values.updateController.enabled }}
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}
